apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: redirect-to-https-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT # Resposta HTTP 301
